namespace Persistence.DatabaseContext.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Correcion : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.CourseLessonLernedsPerStudents", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.CourseLessonLernedsPerStudents", "CreatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.CourseLessonLernedsPerStudents", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.CourseLessonLernedsPerStudents", "UpdatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.CourseLessonLernedsPerStudents", "DeletedAt", c => c.DateTime());
            AddColumn("dbo.CourseLessonLernedsPerStudents", "DeletedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.LessonPerCourses", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.LessonPerCourses", "CreatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.LessonPerCourses", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.LessonPerCourses", "UpdatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.LessonPerCourses", "DeletedAt", c => c.DateTime());
            AddColumn("dbo.LessonPerCourses", "DeletedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.Courses", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Courses", "CreatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.Courses", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Courses", "UpdatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.Courses", "DeletedAt", c => c.DateTime());
            AddColumn("dbo.Courses", "DeletedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.Incomes", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Incomes", "CreatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.Incomes", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Incomes", "UpdatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.Incomes", "DeletedAt", c => c.DateTime());
            AddColumn("dbo.Incomes", "DeletedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.ReviewsPerCourses", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.ReviewsPerCourses", "CreatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.ReviewsPerCourses", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.ReviewsPerCourses", "UpdatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.ReviewsPerCourses", "DeletedAt", c => c.DateTime());
            AddColumn("dbo.ReviewsPerCourses", "DeletedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.UsersPerCourses", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.UsersPerCourses", "CreatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.UsersPerCourses", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.UsersPerCourses", "UpdatedBy", c => c.String(maxLength: 128));
            AddColumn("dbo.UsersPerCourses", "DeletedAt", c => c.DateTime());
            AddColumn("dbo.UsersPerCourses", "DeletedBy", c => c.String(maxLength: 128));
            AlterColumn("dbo.Incomes", "EntityId", c => c.Int(nullable: false));
            CreateIndex("dbo.Courses", "CreatedBy");
            CreateIndex("dbo.Courses", "UpdatedBy");
            CreateIndex("dbo.Courses", "DeletedBy");
            CreateIndex("dbo.LessonPerCourses", "CreatedBy");
            CreateIndex("dbo.LessonPerCourses", "UpdatedBy");
            CreateIndex("dbo.LessonPerCourses", "DeletedBy");
            CreateIndex("dbo.CourseLessonLernedsPerStudents", "CreatedBy");
            CreateIndex("dbo.CourseLessonLernedsPerStudents", "UpdatedBy");
            CreateIndex("dbo.CourseLessonLernedsPerStudents", "DeletedBy");
            CreateIndex("dbo.Incomes", "CreatedBy");
            CreateIndex("dbo.Incomes", "UpdatedBy");
            CreateIndex("dbo.Incomes", "DeletedBy");
            CreateIndex("dbo.ReviewsPerCourses", "CreatedBy");
            CreateIndex("dbo.ReviewsPerCourses", "UpdatedBy");
            CreateIndex("dbo.ReviewsPerCourses", "DeletedBy");
            CreateIndex("dbo.UsersPerCourses", "CreatedBy");
            CreateIndex("dbo.UsersPerCourses", "UpdatedBy");
            CreateIndex("dbo.UsersPerCourses", "DeletedBy");
            AddForeignKey("dbo.Courses", "CreatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Courses", "DeletedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.LessonPerCourses", "CreatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.LessonPerCourses", "DeletedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.LessonPerCourses", "UpdatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Courses", "UpdatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.CourseLessonLernedsPerStudents", "CreatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.CourseLessonLernedsPerStudents", "DeletedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.CourseLessonLernedsPerStudents", "UpdatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Incomes", "CreatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Incomes", "DeletedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Incomes", "UpdatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.ReviewsPerCourses", "CreatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.ReviewsPerCourses", "DeletedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.ReviewsPerCourses", "UpdatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.UsersPerCourses", "CreatedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.UsersPerCourses", "DeletedBy", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.UsersPerCourses", "UpdatedBy", "dbo.AspNetUsers", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.UsersPerCourses", "UpdatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.UsersPerCourses", "DeletedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.UsersPerCourses", "CreatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.ReviewsPerCourses", "UpdatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.ReviewsPerCourses", "DeletedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.ReviewsPerCourses", "CreatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.Incomes", "UpdatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.Incomes", "DeletedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.Incomes", "CreatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.CourseLessonLernedsPerStudents", "UpdatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.CourseLessonLernedsPerStudents", "DeletedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.CourseLessonLernedsPerStudents", "CreatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.Courses", "UpdatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.LessonPerCourses", "UpdatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.LessonPerCourses", "DeletedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.LessonPerCourses", "CreatedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.Courses", "DeletedBy", "dbo.AspNetUsers");
            DropForeignKey("dbo.Courses", "CreatedBy", "dbo.AspNetUsers");
            DropIndex("dbo.UsersPerCourses", new[] { "DeletedBy" });
            DropIndex("dbo.UsersPerCourses", new[] { "UpdatedBy" });
            DropIndex("dbo.UsersPerCourses", new[] { "CreatedBy" });
            DropIndex("dbo.ReviewsPerCourses", new[] { "DeletedBy" });
            DropIndex("dbo.ReviewsPerCourses", new[] { "UpdatedBy" });
            DropIndex("dbo.ReviewsPerCourses", new[] { "CreatedBy" });
            DropIndex("dbo.Incomes", new[] { "DeletedBy" });
            DropIndex("dbo.Incomes", new[] { "UpdatedBy" });
            DropIndex("dbo.Incomes", new[] { "CreatedBy" });
            DropIndex("dbo.CourseLessonLernedsPerStudents", new[] { "DeletedBy" });
            DropIndex("dbo.CourseLessonLernedsPerStudents", new[] { "UpdatedBy" });
            DropIndex("dbo.CourseLessonLernedsPerStudents", new[] { "CreatedBy" });
            DropIndex("dbo.LessonPerCourses", new[] { "DeletedBy" });
            DropIndex("dbo.LessonPerCourses", new[] { "UpdatedBy" });
            DropIndex("dbo.LessonPerCourses", new[] { "CreatedBy" });
            DropIndex("dbo.Courses", new[] { "DeletedBy" });
            DropIndex("dbo.Courses", new[] { "UpdatedBy" });
            DropIndex("dbo.Courses", new[] { "CreatedBy" });
            AlterColumn("dbo.Incomes", "EntityId", c => c.String(nullable: false));
            DropColumn("dbo.UsersPerCourses", "DeletedBy");
            DropColumn("dbo.UsersPerCourses", "DeletedAt");
            DropColumn("dbo.UsersPerCourses", "UpdatedBy");
            DropColumn("dbo.UsersPerCourses", "UpdatedAt");
            DropColumn("dbo.UsersPerCourses", "CreatedBy");
            DropColumn("dbo.UsersPerCourses", "CreatedAt");
            DropColumn("dbo.ReviewsPerCourses", "DeletedBy");
            DropColumn("dbo.ReviewsPerCourses", "DeletedAt");
            DropColumn("dbo.ReviewsPerCourses", "UpdatedBy");
            DropColumn("dbo.ReviewsPerCourses", "UpdatedAt");
            DropColumn("dbo.ReviewsPerCourses", "CreatedBy");
            DropColumn("dbo.ReviewsPerCourses", "CreatedAt");
            DropColumn("dbo.Incomes", "DeletedBy");
            DropColumn("dbo.Incomes", "DeletedAt");
            DropColumn("dbo.Incomes", "UpdatedBy");
            DropColumn("dbo.Incomes", "UpdatedAt");
            DropColumn("dbo.Incomes", "CreatedBy");
            DropColumn("dbo.Incomes", "CreatedAt");
            DropColumn("dbo.Courses", "DeletedBy");
            DropColumn("dbo.Courses", "DeletedAt");
            DropColumn("dbo.Courses", "UpdatedBy");
            DropColumn("dbo.Courses", "UpdatedAt");
            DropColumn("dbo.Courses", "CreatedBy");
            DropColumn("dbo.Courses", "CreatedAt");
            DropColumn("dbo.LessonPerCourses", "DeletedBy");
            DropColumn("dbo.LessonPerCourses", "DeletedAt");
            DropColumn("dbo.LessonPerCourses", "UpdatedBy");
            DropColumn("dbo.LessonPerCourses", "UpdatedAt");
            DropColumn("dbo.LessonPerCourses", "CreatedBy");
            DropColumn("dbo.LessonPerCourses", "CreatedAt");
            DropColumn("dbo.CourseLessonLernedsPerStudents", "DeletedBy");
            DropColumn("dbo.CourseLessonLernedsPerStudents", "DeletedAt");
            DropColumn("dbo.CourseLessonLernedsPerStudents", "UpdatedBy");
            DropColumn("dbo.CourseLessonLernedsPerStudents", "UpdatedAt");
            DropColumn("dbo.CourseLessonLernedsPerStudents", "CreatedBy");
            DropColumn("dbo.CourseLessonLernedsPerStudents", "CreatedAt");
        }
    }
}
